language: java
sudo: false
jdk:
- openjdk8
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_install:
- export TZ=Australia/Canberra
- date
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn deploy'
env:
  global:
  - secure: iAE6fYXASL87o0wB1iV1/IvHRKrsvmVW+DiOQr+uMlRg/D3WmoQWYlkKQ4S1tK6y+9wUiQswLZOObnFnqeZEO+o3ArJ3frY+DgPMna4R5+Wp0BRPGzE7zYZu25Oi/aeKj26NPiVlKUmmL2ZcxPun9dzykPXgyJntlZWQAhdQAgeWEEDTOHmSMj4y3eLnnd/ZPpA2bkUUZ8EV+cXaQXCKlVFa7LmLEtEAvR9Ux+tYqbMCEvr/TBuuj92WCCAyDqsaYpIWLBzT05KYzFSj3C9zGABe0F2vp+rrrCCwvSpPD608HbZSSwWpJZWV2U5k0l5ZNdEHLNIVx4+/Oc8EXiqPm6/PYwkjAfLv5lSlTLhu/wJEaeAYDsrtYC03g0TzNG64n1UqoEQcV50tB7Gexe6+w2OSvJPIMDMpNIrKrbKWb9eCisMLbrlwNq27CwCjvxQLsir6G+YGLXAy3kLagwSTP0tAKPHcCwsFf+NdWb14ztRU8WSsUygCgdE2N6Pjbzxwa6hWpIMD58tx4NXQKxRkv55Te6lWX0fTKpUzheGCcRKJD3O+gZKR0BhzP2fmGkbObtEOEnRkpfXkLTY8XtjilT/FR4vX+xRF4ueY4LBWpRh/4+VGkYzx6FY3cVgsVPFGFZL3GNpMbjyQCJ35Trca1Ux11N3BJdAdG/BEvi4wUfk=
  - secure: RqWtB+4EGrLa8kppkFMYNHixIBRNPNeQm2X8UmNEbjmyH33vIc7TUS07MOfHT2TKSvcvs0fFvWfH9SgLcjQ5phm171LBAgdL76yq0o9DsOJQ1KYLEQFxwHPLLNk5W/8ND6gc8L7afYrOAnfix9zhsR3CTqNx6YRclrm3ZnHtfKhb4ykgoBgrgdqYVZJh8dpKwilvmvvX64RjZkLQBuvNW7x02eGwLKKukePya85fDHgm0uI6glG+fI7RVQWanAleOkdAMx5m7/4eu/U506LqAXSn+ucdOfSLNDEnwdLmJZd+pB+UUtQKe8jlWlvt/l6pAEK8pG9lT5ZiIJXGArLSTG8cMB9at4cls3j2NFE1n6/HwM2jeK8WhVrgt2Pm+qcdTjuj9lMx+X8c1yRYAxjzhMRDXk5a0kPdeT6GZ34aPWr8OsGRUMoZG/4ujcb23/yNZCB1LR7J+gAzV25cBukRS/73rGU4uliYg3+uYAco6gK0JQVPXhuXKw1GQ7D89hzysqskUKyhkUrF+hKUYEOhVoNyIoJ0MWUBojXbOb1mvBmDet7FICavQDi/unHSha+enlyNhLhS6D8tIoVQEQu8EuyFu1GMuSoipNGbGGBYx0fMG+FFYXltSi8EX282Kqgy/cXEzpSY/8MxhmmHA95qp2kmRS8DcLZzKx6bYZQBSvI=
